In [2]:
import my_module

3
3
6
1.3333333333333333


In [3]:
print(my_module.multi(4, 5))

20


### Numpy 라이브러리
- 고성능, 대용량 산술연산을 위해서 사용하는 라이브러리
- ndarray(array, 배열) : list와 비슷한 형태의 자료구조
- 배열은 list보다 빠르고 메모리 효율이 좋음
- 반복문 없이도 배열 전체에 연산 적용 가능

In [4]:
# 라이브러리 사용을 하기 위해서는
# 라이브러리 불러오는 과정을 거쳐야함
# import : 수입하다, (외부에 있는 것을) 불러오다
import numpy as np
# as : alias 별칭을 붙일 때 사용하는 키워드
# numpy를 불러와서 쓸 건데 사용할 때 np라고 짧게 부를게.

In [5]:
# np.array()
# array() : ndarray를 생성하는 함수
# . : dot 연산자, 하위에 있는 것에 접근하려고 할 때 사용하는 연산자
# numpy 아래에 있는 array 생성 함수를 호출함

In [6]:
# 배열 생성
# 리스트를 기반으로 배열 생성
# list1
# 1, 2, 3, 4, 5
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [7]:
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [8]:
# 다차원 배열 선언
# 2차원 배열 생성
list2 = [[1, 2, 3],
        [4, 5, 6]]
print(list2)

arr2 = np.array(list2)

[[1, 2, 3], [4, 5, 6]]


In [9]:
# 배열의 정보 확인하기
# 1. 배열의 모양 : shape
arr1.shape # (5,)
arr2.shape # (2, 3)
# 배열의 모양을 튜플의 형태로 알려줌
# .함수()
# shape : 함수가 아니고 attribute

# 2. 배열의 차원 확인(몇차원인지)
print(arr1.ndim)
print(arr2.ndim)

# 3. 배열에 들어있는 자료들의 자료형
print(arr1.dtype)
print(arr1.dtype)

1
2
int64
int64


In [10]:
# 4. 배열에 들어있는 모든 원소의 개수 : size
print(arr1.size)
print(arr2.size)

5
6


In [11]:
# 1. arr3 생성 -> [1.2, 2.1, 5.9, 6.0]
# 2. arr3의 모양, 차원, 자료형, 모든 요소 개수
arr3 = np.array([1.2, 2.1, 5.9, 6.0])
print(arr3.shape, arr3.ndim, arr3.dtype, arr3.size)

# 3. arr4 생성 -> [['a', 'b', 'c'], ['d', 'e', 'f']]
# 4. arr4의 모양, 차원, 자료형, 모든 요소 개수
arr4 = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
print(arr4.shape, arr4.ndim, arr4.dtype, arr4.size)
# <U1 : (유니코드로 표현된) 글자 1개

(4,) 1 float64 4
(2, 3) 2 <U1 6


In [12]:
# 반복문
# [1, 2, 3, 4, ...., 50]
# 1~50까지 들어있는 배열 생성

# 1. 빈 리스트(list5) 생성
list5 = []

# 2. 반복문 빈 리스트 안에 1~50까지 넣어주세요
i = 1
while i <= 50:
    list5.append(i)
    i += 1

# 3. 생성된 리스트로 배열(arr5) 생성
arr5 = np.array(list5)
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [13]:
# arange : array range
# 원하는 범위만큼의 배열을 생성해줌
# arange(시작값, 끝값, 증감량) : 끝값은 포함되지 않음.
print(np.arange(1, 51, 1))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [14]:
# 배열은 같은 자료형만 포함할 수 있음
# 배열 생성 시 자료형을 지정 가능
# int를 담고 있는 list로 배열 생성을 해도 float으로 생성하겠다라고 말할 수 있음
arr6 = np.array([1, 2, 3], dtype = 'float')
print(arr6.dtype)

float64


In [15]:
# 타입 변환
# float -> int
arr6 = arr6.astype('int32') # 원본 데이터 변경 안 함.
print(arr6.dtype)

int32


### 배열 관련 연산

In [16]:
# 파이썬 list 연산
list1 = [1, 2, 3]
list2 = [4, 5, 6]

print(list1 + list2)
# 리스트 더하기 연산 -> 리스트를 이어 붙여줌

[1, 2, 3, 4, 5, 6]


In [17]:
arr1 = np.array(list1)
arr2 = np.array(list2)

print(arr1, arr2)

# 배열 더하기 연산
print(arr1 + arr2)
# 같은 위치에 있는 요소들끼리 연산
# 그 연산 결과를 array 묶어서 전달
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[1 2 3] [4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
# 배열과 숫자 한 개(스칼라값) 연산
print(arr1 + 7)
# 각 요소 별로 연산을 해서 그 결과를 array 묶어서 전달

[ 8  9 10]


In [19]:
# 비교연산자 : 부등호
print(list1 == list2)
print(arr1 == arr2)
# 각 요소 별로 비교를 해서 그 결과를 array 묶어서 전달

False
[False False False]


### 배열의 인덱싱, 슬라이싱

In [20]:
arr6 = np.array([1, 2, 3, 4])
print(arr6)

[1 2 3 4]


In [21]:
# 배열이름[번호]
# 2
print(arr6[1])

# 4
print(arr6[3])

# 2 역순
print(arr6[-3])

# 4 역순
print(arr6[-1])

2
4
2
4


In [22]:
# 2차원 배열 인덱싱
arr7 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr7)

[[1 2 3]
 [4 5 6]]


In [23]:
# 이차원 배열 인덱싱
# 차례로 차근차근
# [1, 2, 3]에 접근
print(arr7[0][1])

print(arr7[0, 1])

2
2


In [24]:
# 2, 3
print(arr6[1:3])
# 1, 2, 3
print(arr6[:])

[2 3]
[1 2 3 4]


In [25]:
print(arr5)
# 1. 26
print(arr5[25])

# 2. 47
print(arr5[46])

# 3. 38~49
print(arr5[37:49])

# 4. 45~50
print(arr5[44:])

# 5. 5~46까지 2씩 증가하게 가져오기
print(arr5[4:46:2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
26
47
[38 39 40 41 42 43 44 45 46 47 48 49]
[45 46 47 48 49 50]
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45]


### Boolean Indexing
- 지금까지 인덱싱을 할 때는 인덱스(번호)를 사용해서 요소를 가져왔음
- Boolean(True/False)를 활용해서 인덱싱을 해보자.

In [26]:
# 배열 안에서 조건에 맞는 데이터만 가져오는 방법
# 외부에서 데이터를 불러와서 사용할 때 원하는 자료만 필터링할 수 있음
ey_score = np.array([30, 40, 70, 65, 85])
print(ey_score)

# 60점 이하인 데이터는 안 가져오고 싶음
# 60점 이상인 데이터만 필터링.

# [] 안에 조건식 작성해서 각각 요소들이 해당 조건을 만족하는지 전달
print(ey_score[ey_score >= 60])
# 해당 조건식을 만족하는(True)인 요소만 필터링.

[30 40 70 65 85]
[70 65 85]


In [27]:
# 불리언 인덱싱 연습
list3 = [5, 8, 11, 30, 44, 101]
arr3 = np.array(list3)
print(arr3)

# 짝수 데이터만 필터링.
# 짝수의 특징 : 2로 나눴을 때 나머지가 0
print(arr3[arr3 % 2 == 0])

[  5   8  11  30  44 101]
[ 8 30 44]


In [28]:
# 
print(arr5)
# 1~50 3의 배수 출력
# 1. 슬라이싱(증감량 조절)
print(arr5[2::3])

# 2. 불리언 인덱싱
print(arr5[arr5 % 3 == 0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


### 외부 파일 불러와서 연산 실습

In [29]:
# BMI 계산 실습
# 실습에 필요한 키, 몸무게가 들어있는 txt파일을 불러와서 배열로 저장

data = np.loadtxt('./data/height_weight.txt', delimiter = ',') # ./ : 지금 우리가 작업하고 있는 위치

# data라는 배열의 정보 확인
# 모양, 차원, 데이터 타입, 모든 요소 개수
print(data.shape, data.ndim, data.dtype, data.size)

(2, 10) 2 float64 20


In [30]:
# 인덱싱해서 행 별로 따로 저장
height = data[0]
weight = data[1]

In [31]:
# bmi 계산 공식 : 몸무게(kg) / (키(m) * 키(m))
# cm / 100 -> m
height_m = height / 100

bmi = weight / (height_m * height_m)
print(bmi)

[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]


### numpy 내장함수

In [32]:
# 자주 사용하는 함수
# sum
# mean
# sqrt
# abs
# ceil
arr9 = np.array([10, -20, 30, -20, 50])
# arr9의 모든 요소의 합
print(np.sum(arr9))
print(np.mean(arr9))
print(np.sqrt(arr9)) # 제곱근 -> 음수의 제곱근은 실존하지 않기 때문에 경고 발생
# nan : not a number(비어있음)
arr9 = np.abs(arr9)
arr10 = np.sqrt(arr9)
print(np.ceil(arr10))

50
10.0
[3.16227766        nan 5.47722558        nan 7.07106781]
[4. 5. 6. 5. 8.]


C:\Users\notye\AppData\Local\Temp\ipykernel_3276\3867921287.py:11: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr9)) # 제곱근 -> 음수의 제곱근은 실존하지 않기 때문에 경고 발생


In [1]:
import numpy as np

In [2]:
# numpy 최종 실습 : 영화 평점 데이터 분석
# 목적 : 사용자별로 평점을 짜게주는 후하게 주는지 분석
# 전체 사용자의 평균 평점 < 사용자의 평점 : 후하게 주는 사람
# 전체 사용자의 평균 평점 > 사용자의 평점 : 짜게 주는 사람

# 실습 데이터 불러오기.
# genfromtxt : loadtxt 함수와 비슷하지만 결측치 처리가 가능한 함수
rating_data = np.genfromtxt('./data/ratings.txt', delimiter = ',', dtype = 'int')
# 9.78300760e+08 -> 지수 표기법 : 긴 자료를 축양해서 표현하는 방법
# 9.78300760 * 10^8 -> 소수점을 8칸 오른쪽으로 이동하겠다
# 1.19300000e+03 = 1.193 * 10^3 = 1193
# 1.19300000e-03 -> 소수점을 왼쪽으로 3칸 이동
# 1.19300000e-03 = 1.193 * 10^-3 = 0.001193

In [3]:
# 외부 데이터 불러오면 먼저 데이터 확인하는 습관 기르기.
# 모양, 차원, 데이터 타입, 모든 요소 개수
print(rating_data.shape, rating_data.ndim, rating_data.dtype, rating_data.size)

(1000209, 4) 2 int64 4000836


In [4]:
# 전체 사용자의 평균 평점
data_avg = np.mean(rating_data[:, 2])
print(round(data_avg, 2))

3.58


In [5]:
# 사용자 별 평균 평점
# 전체 사용자 별 평균 평점을 구하기 전에, id가 1인 사람의 평균 평점을 구해보자.
# 불리언 인덱싱을 활용해서 사용자 id 부분이 1인 데이터를 필터링

# 1. 사용자 id 부분 가져오기
# 2. id가 1과 일치하는지 확인
# 3. rating_data 불리언 인덱싱 하기.
id_one = rating_data[rating_data[:, 0] == 1]

# 4. id가 1인 사람이 남긴 평점들의 평균 구하기
id_mean = id_one[:, 2].mean()
print(id_mean)

4.188679245283019


In [6]:
# 3947번 id 사용자 평균 평점

# 그 사람의 평균 평점이 전체 평균보다 낮으면
# _번 사용자는 평점을 짜게 줍니다
# 그 사람의 평균 평점이 평균보다 높으면
# _번 사용자는 평점을 후하게 줍니다

if data_avg > rating_data[rating_data[:, 0] == 3947][:, 2].mean():
    print("3947번 사용자는 평점을 짜게 줍니다")
else:
    print("3947번 사용자는 평점을 후하게 줍니다")

3947번 사용자는 평점을 후하게 줍니다


In [14]:
# 모든 아이디 별로 평균 평점 구하기
# 데이터 안에 있는 모든 id를 알아보기
# 1~6040번 사용자들 중에 여러번 평점을 남긴 사람들도 있겠지
# id의 고유한 값 가져오기. -> unique : 고유값을 확인하는 함수
user_id = np.unique(rating_data[:, 0])

# 1. 사용자 아이디와 평균 평점 담을 빈 리스트 생성
# user_id_mean
user_id_mean = []

# 2. user_id 배열 반복문을 통해 순회
# 2-1. id가 i인 사람 필터링
# 2-2. 2-1 필터링한 결과의 평균 평점
# 2-3. [i, 2-2결과]를 user_id_mean 추가

# 빠른 실행, 높은 메모리 사용
print("==================== CPU 최적화 ====================\n빠른 실행, 높은 메모리 사용\n")
maxId = max(user_id)
length = rating_data.shape[0]
temp = [[0.0, 0] for i in range(maxId)]

# 1번째 순회, 평점 총 합과 평점 개수
i = 0
while i < length:
    curId = rating_data[i, 0] - 1
    temp[curId] = [temp[curId][0] + rating_data[i][2], temp[curId][1] + 1]
    i += 1

# 2번째 순회, 평균 구한 후 user_id_mean에 추가
i = 0
while i < maxId:
    if 0 != temp[i][1]:
        user_id_mean.append([i + 1, temp[i][0] / temp[i][1]])
    i += 1

# 불필요한 메모리 해제
del temp

# 3. user_id_mean 사용해 배열 생성
# arr_mean
arr_mean = np.round(np.array(user_id_mean), 2)

# 4. 전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링(불리언 인덱싱)
print("전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링\n", arr_mean[arr_mean[:, 1] > data_avg])



print("\n\n\n")



# 1. 사용자 아이디와 평균 평점 담을 빈 리스트 생성
# user_id_mean
user_id_mean = []

# 2. user_id 배열 반복문을 통해 순회
# 2-1. id가 i인 사람 필터링
# 2-2. 2-1 필터링한 결과의 평균 평점
# 2-3. [i, 2-2결과]를 user_id_mean 추가

# 적은 메모리 사용, 느린 실행
print("==================== 메모리 최적화 ====================\n적은 메모리 사용, 느린 실행\n")
# 순회 횟수 (user_id 길이 * rating_data 길이)
for i in user_id:
    user_id_mean.append([i, rating_data[rating_data[:, 0] == i][:, 2].mean()])

# 3. user_id_mean 사용해 배열 생성
# arr_mean
arr_mean = np.round(np.array(user_id_mean), 2)

# 4. 전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링(불리언 인덱싱)
result1 = arr_mean[arr_mean[:, 1] > data_avg]
print("전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링\n", result1)

==================== CPU 최적화 ====================
빠른 실행, 높은 메모리 사용

전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링
 [[1.000e+00 4.190e+00]
 [2.000e+00 3.710e+00]
 [3.000e+00 3.900e+00]
 ...
 [6.037e+03 3.720e+00]
 [6.038e+03 3.800e+00]
 [6.039e+03 3.880e+00]]




==================== 메모리 최적화 ====================
적은 메모리 사용, 느린 실행

전체 영화 평점보다 사용자 평균 평점이 높은 데이터 필터링
 [[1.000e+00 4.190e+00]
 [2.000e+00 3.710e+00]
 [3.000e+00 3.900e+00]
 ...
 [6.037e+03 3.720e+00]
 [6.038e+03 3.800e+00]
 [6.039e+03 3.880e+00]]


In [12]:
# 5. 전체 영화 평점 평균보다 사용자 평균 평점이 낮거나 같은 데이터 필터링
# 6. 결과 result2 저장
result2 = arr_mean[arr_mean[:, 1] <= data_avg]

# 7. arr_mean(전체 데이터), result2(필터링한 결과) 길이 출력
print(len(arr_mean), len(result2))

6040 2172


In [15]:
# 필터링한 테이터들 파일로 저장
np.savetxt('./data/rank_data1.txt', result1, delimiter = ',', fmt = '%.2f')

In [16]:
# result2 저장
# rank_data2.txt
# delimiter = ',', fmt = '%.2f'
np.savetxt('./data/rank_data2.txt', result2, delimiter = ',', fmt = '%.2f')

In [ ]:
# 주피터 노트북을 다시 껐다가 키면
# 내가 작업했던 모든 것들이 사라진다.
# 1. Kernel > Restart Kernel and Run all cells
# - 위에 에러가 나는 셀이 있으면 모든 셀이 다 실행되지 않음.
# 2. 변수 선언하는 코드만 다시 실행